spring:
  application:
    name: API-Gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: doctor-service
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/api/doctors/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: mysecretkeymysecretkeymysecretkeymysecretkey

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG